import { SimScene } from "./types";

export const scenarios: SimScene[] = [
  // BIKE (5)
  {
    id: "bike_wrong_side",
    category: "bike",
    title: "Wrong-Side Riding",
    prompt: "Move the bike to the correct (left) lane.",
    background: "/sim/env_road_2lane.png",
    draggables: [
      {
        id: "bike",
        sprite: "/sim/veh_bike.png",
        startXY: [600, 300],
        hitbox: [0, 0, 80, 120],
      },
    ],
    targets: [
      {
        id: "left_lane",
        rect: [50, 280, 200, 140],
        accepts: ["bike"],
        label: "Left Lane",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Ride on the left with the traffic flow.",
    wrongTips: ["Wrong lane! Use the left lane."],
    hintTargetId: "left_lane",
  },
  {
    id: "bike_no_helmet",
    category: "bike",
    title: "No Helmet",
    prompt: "Put a helmet on the rider.",
    background: "/sim/env_road_2lane.png",
    overlays: ["/sim/prop_helmet.png"],
    draggables: [
      {
        id: "helmet",
        sprite: "/sim/prop_helmet.png",
        startXY: [100, 100],
        hitbox: [0, 0, 60, 60],
      },
      {
        id: "bike",
        sprite: "/sim/veh_bike.png",
        startXY: [400, 300],
        hitbox: [0, 0, 80, 120],
      },
    ],
    targets: [
      {
        id: "rider_head",
        rect: [400, 280, 80, 40],
        accepts: ["helmet"],
        label: "Rider's Head",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Helmet saves lives—always wear ISI-marked.",
    wrongTips: ["Place the helmet on the rider's head."],
    hintTargetId: "rider_head",
  },
  {
    id: "bike_triple",
    category: "bike",
    title: "Triple Riding",
    prompt: "Remove extra riders.",
    background: "/sim/env_road_2lane.png",
    draggables: [
      {
        id: "bike",
        sprite: "/sim/veh_bike_with_3.png",
        startXY: [400, 300],
        hitbox: [0, 0, 80, 120],
      },
      {
        id: "rider2",
        sprite: "/sim/ped_male.png",
        startXY: [420, 250],
        hitbox: [0, 0, 30, 50],
      },
      {
        id: "rider3",
        sprite: "/sim/ped_female.png",
        startXY: [440, 220],
        hitbox: [0, 0, 30, 50],
      },
    ],
    targets: [
      {
        id: "footpath1",
        rect: [50, 50, 100, 50],
        accepts: ["rider2", "rider3"],
        label: "Footpath",
      },
      {
        id: "footpath2",
        rect: [200, 50, 100, 50],
        accepts: ["rider2", "rider3"],
        label: "Footpath",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Max two persons on a bike.",
    wrongTips: ["Move extra riders to the footpath."],
    hintTargetId: "footpath1",
  },
  {
    id: "bike_signal_jump",
    category: "bike",
    title: "Signal Jumping",
    prompt: "Go behind stop line.",
    background: "/sim/env_intersection.png",
    overlays: ["/sim/prop_signal_red.png", "/sim/prop_stop_line.png"],
    draggables: [
      {
        id: "bike",
        sprite: "/sim/veh_bike.png",
        startXY: [450, 300],
        hitbox: [0, 0, 80, 120],
      },
    ],
    targets: [
      {
        id: "stop_line",
        rect: [200, 320, 150, 20],
        accepts: ["bike"],
        label: "Behind Stop Line",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Stop before the line on red.",
    wrongTips: ["Move behind the stop line."],
    hintTargetId: "stop_line",
  },
  {
    id: "bike_drunk",
    category: "bike",
    title: "Drunk Riding",
    prompt: "Dispose the bottle.",
    background: "/sim/env_road_2lane.png",
    draggables: [
      {
        id: "bike",
        sprite: "/sim/veh_bike.png",
        startXY: [400, 300],
        hitbox: [0, 0, 80, 120],
      },
      {
        id: "bottle",
        sprite: "/sim/prop_bottle.png",
        startXY: [420, 280],
        hitbox: [0, 0, 30, 40],
      },
    ],
    targets: [
      {
        id: "trash",
        rect: [50, 450, 80, 80],
        accepts: ["bottle"],
        label: "Trash",
      },
      {
        id: "police",
        rect: [650, 450, 80, 80],
        accepts: ["bottle"],
        label: "Police Check",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Never drink & ride.",
    wrongTips: ["Dispose the bottle properly."],
    hintTargetId: "trash",
  },
  // CAR (5)
  {
    id: "car_ambulance",
    category: "car",
    title: "Give Way to Ambulance",
    prompt: "Give way to ambulance.",
    background: "/sim/env_road_4lane.png",
    draggables: [
      {
        id: "car",
        sprite: "/sim/veh_car.png",
        startXY: [400, 300],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "ambulance",
        sprite: "/sim/veh_ambulance.png",
        startXY: [450, 300],
        hitbox: [0, 0, 100, 150],
      },
    ],
    targets: [
      {
        id: "side_lane",
        rect: [50, 280, 150, 140],
        accepts: ["car"],
        label: "Side Lane",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Always yield to ambulances.",
    wrongTips: ["Move your car aside to let the ambulance pass."],
    hintTargetId: "side_lane",
  },
  {
    id: "car_zebra_block",
    category: "car",
    title: "Blocking Zebra Crossing",
    prompt: "Keep zebra clear.",
    background: "/sim/env_zebra_crossing.png",
    overlays: ["/sim/prop_signal_red.png", "/sim/prop_stop_line.png"],
    draggables: [
      {
        id: "car",
        sprite: "/sim/veh_car.png",
        startXY: [400, 280],
        hitbox: [0, 0, 100, 150],
      },
    ],
    targets: [
      {
        id: "stop_line",
        rect: [200, 320, 200, 20],
        accepts: ["car"],
        label: "Behind Stop Line",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Keep zebra clear for pedestrians.",
    wrongTips: ["Move behind the stop line."],
    hintTargetId: "stop_line",
  },
  {
    id: "car_school_speed",
    category: "car",
    title: "Overspeeding in School Zone",
    prompt: "Slow to ≤30 in school zone.",
    background: "/sim/env_school_zone.png",
    overlays: ["/sim/prop_sign_speed_30.png"],
    draggables: [
      {
        id: "speed_knob",
        sprite: "/sim/ui_panel.png",
        startXY: [600, 100],
        hitbox: [0, 0, 80, 80],
      },
    ],
    targets: [
      {
        id: "speed_30",
        rect: [300, 200, 200, 100],
        accepts: ["speed_knob"],
        label: "30 km/h Zone",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "≤30 km/h near schools.",
    wrongTips: ["Reduce speed to 30 km/h."],
    hintTargetId: "speed_30",
  },
  {
    id: "car_footpath_park",
    category: "car",
    title: "Parking on Footpath",
    prompt: "Move car to parking bay.",
    background: "/sim/env_sidewalk.png",
    overlays: ["/sim/env_parking_bay.png"],
    draggables: [
      {
        id: "car",
        sprite: "/sim/veh_car.png",
        startXY: [200, 200],
        hitbox: [0, 0, 100, 150],
      },
    ],
    targets: [
      {
        id: "parking_bay",
        rect: [500, 250, 150, 100],
        accepts: ["car"],
        label: "Parking Bay",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Footpaths are for pedestrians.",
    wrongTips: ["Move the car to the parking bay."],
    hintTargetId: "parking_bay",
  },
  {
    id: "car_tailgate",
    category: "car",
    title: "Tailgating (No Distance)",
    prompt: "Maintain safe distance.",
    background: "/sim/env_road_2lane.png",
    draggables: [
      {
        id: "car1",
        sprite: "/sim/veh_car.png",
        startXY: [400, 200],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "car2",
        sprite: "/sim/veh_car.png",
        startXY: [420, 350],
        hitbox: [0, 0, 100, 150],
      },
    ],
    targets: [
      {
        id: "two_sec_marker",
        rect: [400, 400, 100, 20],
        accepts: ["car2"],
        label: "2-Second Rule Marker",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Maintain safe following distance.",
    wrongTips: ["Keep at least 2 seconds distance."],
    hintTargetId: "two_sec_marker",
  },
  // PEDESTRIAN (4)
  {
    id: "ped_jaywalk",
    category: "pedestrian",
    title: "Jaywalking",
    prompt: "Use the zebra crossing.",
    background: "/sim/env_road_2lane.png",
    overlays: ["/sim/env_zebra_crossing.png"],
    draggables: [
      {
        id: "pedestrian",
        sprite: "/sim/ped_male.png",
        startXY: [300, 200],
        hitbox: [0, 0, 30, 50],
      },
    ],
    targets: [
      {
        id: "zebra",
        rect: [350, 280, 100, 40],
        accepts: ["pedestrian"],
        label: "Zebra Crossing",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Cross only at zebra crossings.",
    wrongTips: ["Use the zebra crossing to cross safely."],
    hintTargetId: "zebra",
  },
  {
    id: "ped_phone",
    category: "pedestrian",
    title: "Phone While Crossing",
    prompt: "No phone while crossing.",
    background: "/sim/env_zebra_crossing.png",
    draggables: [
      {
        id: "pedestrian",
        sprite: "/sim/ped_phone_pose.png",
        startXY: [400, 280],
        hitbox: [0, 0, 30, 50],
      },
      {
        id: "phone",
        sprite: "/sim/prop_phone.png",
        startXY: [420, 270],
        hitbox: [0, 0, 25, 40],
      },
    ],
    targets: [
      {
        id: "trash",
        rect: [50, 450, 80, 80],
        accepts: ["phone"],
        label: "Trash",
      },
      {
        id: "wait_area",
        rect: [200, 450, 100, 50],
        accepts: ["pedestrian"],
        label: "Waiting Area",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Heads up—no phones while crossing.",
    wrongTips: ["Put away the phone or wait before crossing."],
    hintTargetId: "trash",
  },
  {
    id: "ped_on_green",
    category: "pedestrian",
    title: "Crossing on Vehicle Green",
    prompt: "Wait for walk signal.",
    background: "/sim/env_intersection.png",
    overlays: ["/sim/prop_signal_green.png", "/sim/prop_signal_ped_stop.png"],
    draggables: [
      {
        id: "pedestrian",
        sprite: "/sim/ped_male.png",
        startXY: [400, 280],
        hitbox: [0, 0, 30, 50],
      },
    ],
    targets: [
      {
        id: "wait_area",
        rect: [200, 450, 150, 50],
        accepts: ["pedestrian"],
        label: "Waiting Area",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Wait for walk signal.",
    wrongTips: ["Wait for the pedestrian walk signal."],
    hintTargetId: "wait_area",
  },
  {
    id: "ped_no_footpath",
    category: "pedestrian",
    title: "Walking on Road, Not Footpath",
    prompt: "Walk on footpath.",
    background: "/sim/env_road_2lane.png",
    overlays: ["/sim/env_sidewalk.png"],
    draggables: [
      {
        id: "pedestrian",
        sprite: "/sim/ped_female.png",
        startXY: [400, 300],
        hitbox: [0, 0, 30, 50],
      },
    ],
    targets: [
      {
        id: "footpath",
        rect: [50, 50, 200, 50],
        accepts: ["pedestrian"],
        label: "Footpath",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Use footpaths for safety.",
    wrongTips: ["Move to the footpath."],
    hintTargetId: "footpath",
  },
  // OTHER (3)
  {
    id: "other_drunk_car",
    category: "other",
    title: "Drunk Driving (Car)",
    prompt: "Remove bottle—no drunk driving.",
    background: "/sim/env_road_2lane.png",
    draggables: [
      {
        id: "car",
        sprite: "/sim/veh_car.png",
        startXY: [400, 300],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "bottle",
        sprite: "/sim/prop_bottle.png",
        startXY: [420, 280],
        hitbox: [0, 0, 30, 40],
      },
    ],
    targets: [
      {
        id: "trash",
        rect: [50, 450, 80, 80],
        accepts: ["bottle"],
        label: "Trash",
      },
      {
        id: "police",
        rect: [650, 450, 80, 80],
        accepts: ["bottle"],
        label: "Police Check",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Never drink & drive.",
    wrongTips: ["Dispose the bottle properly."],
    hintTargetId: "trash",
  },
  {
    id: "other_block_fire",
    category: "other",
    title: "Blocking Fire Truck",
    prompt: "Clear path for fire truck.",
    background: "/sim/env_road_4lane.png",
    draggables: [
      {
        id: "car1",
        sprite: "/sim/veh_car.png",
        startXY: [400, 300],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "car2",
        sprite: "/sim/veh_car.png",
        startXY: [450, 300],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "fire_truck",
        sprite: "/sim/veh_fire_truck.png",
        startXY: [500, 300],
        hitbox: [0, 0, 120, 150],
      },
    ],
    targets: [
      {
        id: "clear_path1",
        rect: [50, 280, 150, 140],
        accepts: ["car1", "car2"],
        label: "Clear Lane",
      },
      {
        id: "clear_path2",
        rect: [600, 280, 150, 140],
        accepts: ["car1", "car2"],
        label: "Clear Lane",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "Clear way for emergency vehicles.",
    wrongTips: ["Move blocking vehicles aside."],
    hintTargetId: "clear_path1",
  },
  {
    id: "other_zigzag",
    category: "other",
    title: "Rash Zig-Zag Overtakes (Bike)",
    prompt: "Stop zig-zag; keep your lane.",
    background: "/sim/env_road_4lane.png",
    draggables: [
      {
        id: "bike",
        sprite: "/sim/veh_bike.png",
        startXY: [350, 250],
        hitbox: [0, 0, 80, 120],
      },
      {
        id: "car1",
        sprite: "/sim/veh_car.png",
        startXY: [400, 300],
        hitbox: [0, 0, 100, 150],
      },
      {
        id: "car2",
        sprite: "/sim/veh_car.png",
        startXY: [500, 300],
        hitbox: [0, 0, 100, 150],
      },
    ],
    targets: [
      {
        id: "correct_lane",
        rect: [200, 280, 150, 140],
        accepts: ["bike"],
        label: "Correct Lane",
      },
    ],
    timeoutHintSeconds: 10,
    timeLimitSeconds: 45,
    maxAttempts: 3,
    successText: "No zig-zag; overtake safely.",
    wrongTips: ["Stay in your lane."],
    hintTargetId: "correct_lane",
  },
];

export const getScenariosByCategory = (category: string) => {
  return scenarios.filter((s) => s.category === category);
};





